import {
  IceCream,
  Cookie,
  Candy,
  Droplet,
  Flame,
  Milk,
  Cherry,
  Nut,
  CupSoda,
  UtensilsCrossed,
  FileText,
  GlassWater,
  CircleDot,
  Hand,
  SprayCan,
  Package,
  Sparkles,
} from 'lucide-react-native';
import {InventoryData} from "@/types/inventory";

export const INVENTORY_DATA: InventoryData = {
  toppings: [
    { id: 2, name: 'Sprinkles', icon: Sparkles, quantity: 0, unit: '' },
    { id: 3, name: 'Crushed Oreos', icon: Cookie, quantity: 0, unit: '' },
    { id: 4, name: 'Gummy Bears', icon: Candy, quantity: 0, unit: '' },
    { id: 5, name: 'Caramel Sauce', icon: Droplet, quantity: 0, unit: '' },
    { id: 6, name: 'Hot Fudge', icon: Flame, quantity: 0, unit: '' },
    { id: 7, name: 'Whipped Cream', icon: Milk, quantity: 0, unit: '' },
    { id: 8, name: 'Cherries', icon: Cherry, quantity: 0, unit: '' },
    { id: 9, name: 'Peanuts', icon: Nut, quantity: 0, unit: '' },
  ],
  flavors: [
    { id: 10, name: 'Vanilla', icon: IceCream, quantity: 0, unit: '' },
    { id: 12, name: 'Cherry', icon: Cherry, quantity: 0, unit: '' },
    { id: 13, name: 'Mint Chip', icon: IceCream, quantity: 0, unit: '' },
    { id: 14, name: 'Cookie Dough', icon: Cookie, quantity: 0, unit: '' },
    { id: 15, name: 'Rocky Road', icon: IceCream, quantity: 0, unit: '' },
    { id: 16, name: 'Butter Pecan', icon: Nut, quantity: 0, unit: '' },
    { id: 17, name: 'Pistachio', icon: Nut, quantity: 0, unit: '' },
    { id: 18, name: 'Coffee', icon: CupSoda, quantity: 0, unit: '' },
  ],
  supplies: [
    { id: 25, name: 'Spoons', icon: UtensilsCrossed, quantity: 0, unit: '' },
    { id: 26, name: 'Napkins', icon: FileText, quantity: 0, unit: '' },
    { id: 27, name: 'Cups (Small)', icon: GlassWater, quantity: 0, unit: '' },
    { id: 28, name: 'Cups (Large)', icon: GlassWater, quantity: 0, unit: '' },
    { id: 29, name: 'Lids', icon: CircleDot, quantity: 0, unit: '' },
    { id: 31, name: 'Gloves', icon: Hand, quantity: 0, unit: '' },
    { id: 32, name: 'Cleaning Spray', icon: SprayCan, quantity: 0, unit: '' },
    { id: 33, name: 'Paper Towels', icon: Package, quantity: 0, unit: '' },
  ],
};
