import { InventoryData } from '@/types/inventory';
import {
  IconSparkles,
  IconCookie,
  IconCandy,
  IconDroplet,
  IconFlame,
  IconMilk,
  IconCherry,
  IconNut,
  IconIceCream,
  IconIceCream2,
  IconCup,
  IconBowl,
  IconCake,
  IconBaguette,
  IconToolsKitchen2,
  IconFileText,
  IconGlass,
  IconGlassFull,
  IconCircleFilled,
  IconHandStop,
  IconSpray,
  IconPaperBag,
} from '@tabler/icons-react-native';

export const INVENTORY_DATA: InventoryData = {
  toppings: [
    { id: 2, name: 'Sprinkles', icon: IconSparkles, quantity: 0, unit: 'oz' },
    { id: 3, name: 'Crushed Oreos', icon: IconCookie, quantity: 0, unit: 'oz' },
    { id: 4, name: 'Gummy Bears', icon: IconCandy, quantity: 0, unit: 'oz' },
    { id: 5, name: 'Caramel Sauce', icon: IconDroplet, quantity: 0, unit: 'oz' },
    { id: 6, name: 'Hot Fudge', icon: IconFlame, quantity: 0, unit: 'oz' },
    { id: 7, name: 'Whipped Cream', icon: IconMilk, quantity: 0, unit: 'cans' },
    { id: 8, name: 'Cherries', icon: IconCherry, quantity: 0, unit: 'oz' },
    { id: 9, name: 'Peanuts', icon: IconNut, quantity: 0, unit: 'oz' },
  ],
  flavors: [
    { id: 10, name: 'Vanilla', icon: IconIceCream, quantity: 0, unit: 'gallons' },
    { id: 12, name: 'Strawberry', icon: IconCherry, quantity: 0, unit: 'gallons' },
    { id: 13, name: 'Mint Chip', icon: IconIceCream2, quantity: 0, unit: 'gallons' },
    { id: 14, name: 'Cookie Dough', icon: IconCookie, quantity: 0, unit: 'gallons' },
    { id: 15, name: 'Rocky Road', icon: IconIceCream, quantity: 0, unit: 'gallons' },
    { id: 16, name: 'Butter Pecan', icon: IconNut, quantity: 0, unit: 'gallons' },
    { id: 17, name: 'Pistachio', icon: IconNut, quantity: 0, unit: 'gallons' },
    { id: 18, name: 'Coffee', icon: IconCup, quantity: 0, unit: 'gallons' },
  ],
  cones: [
    { id: 19, name: 'Waffle Cone', icon: IconIceCream2, quantity: 0, unit: 'count' },
    { id: 20, name: 'Sugar Cone', icon: IconIceCream, quantity: 0, unit: 'count' },
    { id: 21, name: 'Cup', icon: IconCup, quantity: 0, unit: 'count' },
    { id: 22, name: 'Waffle Bowl', icon: IconBowl, quantity: 0, unit: 'count' },
    { id: 23, name: 'Cake Cone', icon: IconCake, quantity: 0, unit: 'count' },
    { id: 24, name: 'Pretzel Cone', icon: IconBaguette, quantity: 0, unit: 'count' },
  ],
  supplies: [
    { id: 25, name: 'Spoons', icon: IconToolsKitchen2, quantity: 0, unit: 'count' },
    { id: 26, name: 'Napkins', icon: IconFileText, quantity: 0, unit: 'packs' },
    { id: 27, name: 'Cups (Small)', icon: IconGlass, quantity: 0, unit: 'count' },
    { id: 28, name: 'Cups (Large)', icon: IconGlassFull, quantity: 0, unit: 'count' },
    { id: 29, name: 'Lids', icon: IconCircleFilled, quantity: 0, unit: 'count' },
    { id: 31, name: 'Gloves', icon: IconHandStop, quantity: 0, unit: 'boxes' },
    { id: 32, name: 'Cleaning Spray', icon: IconSpray, quantity: 0, unit: 'bottles' },
    { id: 33, name: 'Paper Towels', icon: IconPaperBag, quantity: 0, unit: 'rolls' },
  ],
};